# Generated by Django 4.1.4 on 2022-12-23 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('campaign_info', '0001_initial'), ('campaign_info', '0002_npc_campaigns'), ('campaign_info', '0003_auto_20210704_2115'), ('campaign_info', '0004_note_post_date'), ('campaign_info', '0005_auto_20210708_2355'), ('campaign_info', '0006_alter_npc_campaigns')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('world_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.world')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.country')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('str_attr', models.SmallIntegerField()),
                ('dex_attr', models.SmallIntegerField()),
                ('con_attr', models.SmallIntegerField()),
                ('wis_attr', models.SmallIntegerField()),
                ('int_attr', models.SmallIntegerField()),
                ('cha_attr', models.SmallIntegerField()),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_info.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaign_info.world'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_txt', models.CharField(max_length=512)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.campaign')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('npc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description_text', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=16)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_info.city')),
                ('campaigns', models.ManyToManyField(blank=True, to='campaign_info.campaign')),
            ],
        ),
    ]
