# Generated by Django 3.2.5 on 2021-07-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('world_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('npc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description_text', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=16)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_info.city')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.world')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.country'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('str_attr', models.SmallIntegerField()),
                ('dex_attr', models.SmallIntegerField()),
                ('con_attr', models.SmallIntegerField()),
                ('wis_attr', models.SmallIntegerField()),
                ('int_attr', models.SmallIntegerField()),
                ('cha_attr', models.SmallIntegerField()),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_info.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campaign_info.world'),
        ),
    ]
