# Generated by Django 3.2.5 on 2021-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='campaigns',
            field=models.ManyToManyField(to='campaign_info.Campaign'),
        ),
    ]
