# Generated by Django 3.2.5 on 2021-07-05 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_info', '0002_npc_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaign_info.world'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_txt', models.CharField(max_length=512)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.campaign')),
            ],
        ),
    ]
