# Generated by Django 3.2.5 on 2021-07-06 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_info', '0003_auto_20210704_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
