# Generated by Django 3.2.5 on 2021-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_info', '0005_auto_20210708_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='campaign_info.Campaign'),
        ),
    ]
