# Generated by Django 4.1.4 on 2023-01-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_info', '0007_campaign_join_code_campaignrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrole',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_info.campaign'),
        ),
    ]
